"""init

Revision ID: 0.0.1
Revises: 
Create Date: 2025-06-26 09:08:48.090184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0.0.1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webclient_nojs_view',
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('view_type', sa.String(length=255), nullable=True),
    sa.Column('xml', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webclient_nojs_view')
    # ### end Alembic commands ###
