"""add action and menuitem

Revision ID: 0.0.3
Revises: 0.0.2
Create Date: 2025-08-09 17:35:14.647903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0.0.3'
down_revision: Union[str, None] = '0.0.2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webclient_action',
    sa.Column('view_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['view_id'], ['webclient_view.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webclient_menuitem',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['webclient_action.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['webclient_menuitem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webclient_menuitem')
    op.drop_table('webclient_action')
    # ### end Alembic commands ###
