"""rename models and remove view type

Revision ID: 0.0.2
Revises: 0.0.1
Create Date: 2025-08-07 23:14:24.383930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0.0.2'
down_revision: Union[str, None] = '0.0.1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('view', 'webclient_view')
    with op.batch_alter_table('webclient_view') as batch_op:
        batch_op.drop_column('type_id')
    op.drop_table('view_type')
    op.execute(
        """
        UPDATE core_xmlid
        SET model_name = 'webclient.view'
        WHERE model_name = 'view'
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE core_xmlid
        SET model_name = 'view'
        WHERE model_name = 'webclient.view'
        """
    )
    op.create_table('view_type',
    sa.Column('component_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('webclient_view') as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_view_type_id', 'view_type', ['type_id'], ['id'],
        )
    op.rename_table('webclient_view', 'view')
    # ### end Alembic commands ###
