"""init

Revision ID: 0.0.1
Revises: 
Create Date: 2025-06-25 23:23:17.142615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0.0.1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template',
    sa.Column('xml', sa.Text(), nullable=True),
    sa.Column('inherit_id', sa.Integer(), nullable=True),
    sa.Column('inherit_mode', sa.String(length=255), nullable=True),
    sa.Column('inherit_sequence', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inherit_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xmlid',
    sa.Column('xmlid', sa.String(length=255), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('source_module', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xmlid')
    op.drop_table('template')
    op.drop_table('module')
    # ### end Alembic commands ###
