"""rename models

Revision ID: 0.0.2
Revises: 0.0.1
Create Date: 2025-08-08 00:45:59.264494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0.0.2'
down_revision: Union[str, None] = '0.0.1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('module', 'core_module')
    op.rename_table('template', 'core_template')
    op.rename_table('xmlid', 'core_xmlid')
    for m in ["module", "template", "xmlid"]:
        op.execute(
            f"""
            UPDATE core_xmlid
            SET model_name = 'core.{m}'
            WHERE model_name = '{m}'
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('core_xmlid', 'xmlid')
    op.rename_table('core_template', 'template')
    op.rename_table('core_module', 'module')
    for m in ["xmlid", "template", "module"]:
        op.execute(
            f"""
            UPDATE xmlid
            SET model_name = '{m}'
            WHERE model_name = 'core.{m}'
            """
        )
    # ### end Alembic commands ###
